### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#272]
Things to do for release:
- [x] Update spiner
- [x] Update ports-of-call
- [x] Merge in #246. Person responsible: @mauneyc-LANL 
- [x] Merge in #245. Person responsible: @dholladay00 
- [x] Merge in #278. Person responsible: @jhp-lanl

**Comment by jhp-lanl** [comment]
@annapiegra do you have an ETA on https://github.com/lanl/singularity-eos/pull/278? I think we can do a minor version release after this one if you need significantly more time. I think @dholladay00 's MR will be sometime next week I'd imagine

**Comment by annapiegra** [comment]
I need to add warnings for minenergy fucntions in debug mode (will do by the end of the week) and docs. This still needs the new spack env since the spiner dependencies in the singularity_eos.f90 are hacked away and the spack mr will fix them.

--
Anna Pietarila Graham
Deputy Group Leader - HPC-ENV

Los Alamos National Laboratory
***@***.******@***.***>
Pronouns: she/her
505-667-5785 (onsite Mon-Wed)



From: Jeff Peterson ***@***.***>
Reply-To: lanl/singularity-eos ***@***.***>
Date: Thursday, August 3, 2023 at 9:53 AM
To: lanl/singularity-eos ***@***.***>
Cc: Anna Pietarila Graham ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lanl/singularity-eos] Release (Issue #272)


@annapiegra<https://urldefense.com/v3/__https:/github.com/annapiegra__;!!Bt8fGhp8LhKGRg!FVQ6Oauw2-VdPgCT6VJHlJ9Gg68a39E7K31K1Q6mg9_6ed-9PjiIU8dtTL5L-27y71iyxBPoR7Dq5Ih2C1dNO3M$> do you have an ETA on #278<https://urldefense.com/v3/__https:/github.com/lanl/singularity-eos/pull/278__;!!Bt8fGhp8LhKGRg!FVQ6Oauw2-VdPgCT6VJHlJ9Gg68a39E7K31K1Q6mg9_6ed-9PjiIU8dtTL5L-27y71iyxBPoR7Dq5Ih2fMN-cFo$>? I think we can do a minor version release after this one if you need significantly more time. I think @dholladay00<https://urldefense.com/v3/__https:/github.com/dholladay00__;!!Bt8fGhp8LhKGRg!FVQ6Oauw2-VdPgCT6VJHlJ9Gg68a39E7K31K1Q6mg9_6ed-9PjiIU8dtTL5L-27y71iyxBPoR7Dq5Ih2rinLu7M$> 's MR will be sometime next week I'd imagine

**Comment by jhp-lanl** [comment]
FYI @Yurlungur since #246 makes spiner optional, I think the spack isn't completely consistent with the CMake as I'm running into some missing spiner symbols when I try to link to singularity-eos. I'll make an MR to fix this sometime this week, but I'd want to get this in before the release

**Comment by dholladay00** [comment]
this is done.
