### ISSUE TITLE
3T roadmap

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#440]
- [x] Implement `MeanAtomicMass` and `MeanAtomicNumber` #439 
- [x] Implement Z-split modifier #444 
  - z-split at least needs to take ionization fraction as an input in the lambda
  - z-split requires mean atomic mass/number of parent, unionized EOS
- [x] Implement ability to load sub-tables of sesame into EOSPAC/spiner #459 
- [ ] Ability to compute ionization level/fraction has to be hot-swappable not monolithic in the EOS 
  - Biggest unknown here.
  - Potentially implement these calculations in downstream first? But would like to move that optionality into something singularity-like long term.
  - Could go in new directory of singularity-eos or in singularity-eos-extras maybe?

**Comment by jhp-lanl** [comment]
As I understand, there are at least two ways to do the Z-split. One would be to use one EOS and just scale the electron contribution by ionization state, but you can also imagine a separate EOS for the electrons and the ions. Would this approach be able to do either?

**Comment by Yurlungur** [comment]
> As I understand, there are at least two ways to do the Z-split. One would be to use one EOS and just scale the electron contribution by ionization state, but you can also imagine a separate EOS for the electrons and the ions. Would this approach be able to do either?

The version I was imagining was the latter. I was thinking of creating two modifiers, `ZSplitElectrons` and `ZSplitIons` that both modify a single original EOS (say Gruneisen). 

That said, if we're interested in supporting the former case too, we could discuss. I'm not sure how to do that generically.

**Comment by jhp-lanl** [comment]
> The version I was imagining was the latter. I was thinking of creating two modifiers, `ZSplitElectrons` and `ZSplitIons` that both modify a single original EOS (say Gruneisen).
> 
> That said, if we're interested in supporting the former case too, we could discuss. I'm not sure how to do that generically.

I'm a little confused here since this sounds like the one EOS case I mentioned. I was thinking that another approach would be to model the electron contribution directly as an ideal gas an pair that with a more appropriate EOS for the ions.

**Comment by Yurlungur** [comment]
Ah ok. After clarifying on Mattermost:
- The implicit assumption is we always hand the host code two EOS's, one electron and one ion
- In zsplit mode, we split an underlying EOS into an electron EOS and an ion EOS
- Alternatively, we may pass two completely separate EOS's to the host code, one for electrons and one for ions
  - To support this, we need ways to load the relevant subtables from Sesame
  - We also need to be able to rescale, say, an ideal gas, by ionization state so the number density is right.

I think we need to support both models.

**Comment by Yurlungur** [comment]
Ionization level/fraction is not yet in singularity-eos. However, I'm closing this issue for now. I think we got there.
